# NumPy


In [1]:
%pip install numpy

import numpy as np
print(np.__version__)

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

arr_from_tuple = np.array(('a', 'b', 'c'))
print(arr_from_tuple)
print(type(arr_from_tuple))

Note: you may need to restart the kernel to use updated packages.
2.4.1
[1 2 3 4]
<class 'numpy.ndarray'>
['a' 'b' 'c']
<class 'numpy.ndarray'>


## Array Dimensions

In [2]:

     
# -------------------------
# 0D array (Scalar)
# -------------------------
# A single value with no dimensions
arr_0d = np.array(10)
print(arr_0d)
print("Dimensions:", arr_0d.ndim)

# -------------------------
# 1D array (Vector)
# -------------------------
# A classic one-dimensional array made of scalar values
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)
print("Dimensions:", arr_1d.ndim)

# -------------------------
# 2D array (Matrix)
# -------------------------
# An array made of 1D arrays (rows and columns)
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr_2d)
print("Dimensions:", arr_2d.ndim)

# -------------------------
# 3D array (Tensor)
# -------------------------
# An array made of 2D arrays
arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
])
print(arr_3d)
print("Dimensions:", arr_3d.ndim)

# -------------------------
# Higher-dimensional array
# -------------------------
# Force a minimum of 10 dimensions
more_dimensions = np.array([1, 2, 3], ndmin=10)
print(more_dimensions)
print("Dimensions:", more_dimensions.ndim)





10
Dimensions: 0
[1 2 3 4]
Dimensions: 1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions: 2
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimensions: 3
[[[[[[[[[[1 2 3]]]]]]]]]]
Dimensions: 10


## Building arrays

In [4]:
# -------------------------
# full(shape, value)
# -------------------------
# Create an array filled with a specific value
arr_full = np.full((3, 2, 1), 'x')
print("full", arr_full)

# -------------------------
# zeros(shape)
# -------------------------
# Create an array filled with zeros
arr_zeros = np.zeros((3, 3, 3))
print("zeroes", arr_zeros)

# -------------------------
# ones(shape)
# -------------------------
# Create an array filled with ones
arr_ones = np.ones((3, 3))
print("ones", arr_ones)

# -------------------------
# arange(start, stop, step)
# -------------------------
# Create values from start to stop (exclusive) using a step size
arr_arange = np.arange(10, 100, 10)
print("arange", arr_arange)

# -------------------------
# linspace(start, stop, num)
# -------------------------
# Create evenly spaced values between two numbers (inclusive)
arr_linspace = np.linspace(20, 50, 6)
print("linspace", arr_linspace)

# -------------------------
# empty(shape) + fill(value)
# -------------------------
# Create an uninitialized array, then fill it
arr_empty = np.empty((5, 5))
arr_empty.fill(1)
print("empty", arr_empty)





full [[['x']
  ['x']]

 [['x']
  ['x']]

 [['x']
  ['x']]]
zeroes [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
ones [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arange [10 20 30 40 50 60 70 80 90]
linspace [20. 26. 32. 38. 44. 50.]
empty [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Looking at the Shape of an Array

NumPy arrays have a shape, which describes the number of dimensions and the size of each dimension.

In [5]:
#Shape
arr = np.array([[
  [1,2,3],
  [4,5,6],
  [7,8,9]
],[
  [1,2,3],
  [4,5,6],
  [7,8,9]
]] )
print(arr.shape)

(2, 3, 3)


(2, 3, 3) → 2 layers, each with 3 rows and 3 columns

In other words:
- There are 2 two-dimensional arrays
- Each 2D array contains 3 one-dimensional arrays (rows)
- Each 1D array contains 3 zero-dimensional values (scalars)

In [6]:
# -------------------------
# Reshape
# -------------------------
# Reshaping changes the shape of an array WITHOUT changing its data.
# The total number of elements must stay the same.
#
# Examples:
# 3 × 3 = 9 elements
# 3 × 1 × 3 = 9 elements
# 9 × 1 = 9 elements

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped_1 = arr.reshape(3, 3)
print(reshaped_1)

# -------------------------
# More reshape examples
# -------------------------
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

reshaped_2 = arr.reshape(2, 3, 2)
reshaped_3 = arr.reshape(4, 3)

print(reshaped_2)
print(reshaped_3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Your Turn

Create a NumPy array containing 10 elements. Practice reshaping it into as many different valid shapes as possible.


In [9]:
my_arr = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

ny_arr = my_arr.reshape(2, 5)
oy_arr = my_arr.reshape(5, 2)
py_arr = my_arr.reshape(10, 1)

print(my_arr)
print(ny_arr)
print(oy_arr)
print(py_arr)

[ 2  3  5  7 11 13 17 19 23 29]
[[ 2  3  5  7 11]
 [13 17 19 23 29]]
[[ 2  3]
 [ 5  7]
 [11 13]
 [17 19]
 [23 29]]
[[ 2]
 [ 3]
 [ 5]
 [ 7]
 [11]
 [13]
 [17]
 [19]
 [23]
 [29]]


## Array indexing 

In [10]:

arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [7, 8, 9],
        [10, 11, 12],
    ],
])

# First 2D array
print(arr[0])

# First row of the first 2D array
print(arr[0][0])

# First element of the first row
print(arr[0][0][0])

# First 2D array, second row
print(arr[0, 1])

# Second 2D array, second row, second element
print(arr[1, 1, 1])


[[1 2 3]
 [4 5 6]]
[1 2 3]
1
[4 5 6]
11


## Slicing

In [ ]:

# Slicing syntax
# [start : end : step]

arr = np.array([1, 2, 3, 4, 5, 6])

# First three elements
print(arr[:3])

# From index 3 to the end
print(arr[3:])

# Every other element
print(arr[::2])

# Every other element, starting at index 1
print(arr[1::2])

# Slice using negative indices
print(arr[-4:-2])






## Your turn: 
Slice this from the array below this
 [[ 1,  3],
  [ 7,  9]]

# Looping through arrays
NumPy has tools that reduce the need for loops, but let’s take a look at how this works in vanilla Python.

In [16]:

#exit ticket
a = np.array([1, 5, 3])
b = np.array([2, 2, 3])
print(a > b)

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

for i in arr:
    print("axis 0:", i)

for i in arr:
    for j in i:
        print(j)


[False  True False]
axis 0: [1 2 3]
axis 0: [4 5 6]
axis 0: [7 8 9]
axis 0: [1 2 3]
axis 0: [4 5 6]
axis 0: [7 8 9]
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9


Lets make it easier

In [12]:
# nditer
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

# Iterate over every element in the 2D array
for i in np.nditer(arr):
    print(i)

arr = np.array([
    [
        [1, 2],
        [3, 4],
    ],
    [
        [5, 6],
        [7, 8],
    ],
])

# Iterate over every element in the 3D array
for x in np.nditer(arr):
    print(x)



1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8


## Joining Arrays


In [13]:
# Join
# SQL joins are based on keys. In NumPy, joins are based on axes.

nums1 = np.array([1, 2, 3])
nums2 = np.array([1, 2, 3])

all_nums = np.concatenate((nums1, nums2))
print(all_nums)

[1 2 3 1 2 3]


In [14]:
nums1_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

nums2_2d = np.array([
    [5, 6, 7],
    [8, 9, 10],
])

all_nums_ax0 = np.concatenate((nums1_2d, nums2_2d), axis=0)
all_nums_ax1 = np.concatenate((nums1_2d, nums2_2d), axis=1)

print(all_nums_ax0)
print(all_nums_ax1)



[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [ 8  9 10]]
[[ 1  2  3  5  6  7]
 [ 4  5  6  8  9 10]]


In [15]:

nums1_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

nums2_2d = np.array([
    [5, 6, 7],
    [8, 9, 10],
])

# Stacks
# Adds a new axis
stack = np.stack((nums1_2d, nums2_2d))
print(stack)

# Joins arrays vertically (axis 0)
vstack = np.vstack((nums1_2d, nums2_2d))
print(vstack)

# Joins arrays side by side (axis 1)
hstack = np.hstack((nums1_2d, nums2_2d))
print(hstack)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [ 8  9 10]]
[[ 1  2  3  5  6  7]
 [ 4  5  6  8  9 10]]


## Splitting arrays

## Where 
Who needs loops when you have where

## Your Turn

Given the array below, use np.where() to find the indices of all values that are between 0.3 and 0.7 (inclusive).
arr = np.array([0.15, 0.32, 0.58, 0.71, 0.44, 0.89, 0.67])
Hint you can use the '&' operator 


## Comparing 

## Boolean Indexing
Boolean indexing can simplify data for ML models.

## Conditions 


## Math
- mean
- sum - total
- cumsum - sum as we go